server:
  port: 10001
spring:
  application:
    name: gateway-encrypt

  cloud:
    gateway:
      routes:
        - id: host_route
          uri: http://example.org
          predicates:
            - Path=/foo/{segment},/bar/{segment}

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:9001/eureka
    fetch-registry: false
  instance:
    prefer-ip-address: true


