server:
  port: 10001
spring:
  application:
    name: gateway-encrypt

  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]': # 匹配所有请求
            allowedOrigins: "*" #跨域处理 允许所有的域
            allowedMethods: # 支持的方法
              - GET
              - POST
              - PUT
              - DELETE
      routes:
        #文章微服务的网关配置
        - id: article_route
          uri: lb://article
          predicates:
            - Path=/article/**,/channel/**,/item/**
          filters:
            #- StripPrefix=1

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:9001/eureka
    fetch-registry: true
  instance:
    prefer-ip-address: true


