server:
  port: 9001
spring:
  application:
    name: eureka1
eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://127.0.0.1:9001/eureka
    fetch-registry: false
  instance:
    prefer-ip-address: true
